### ISSUE TITLE
export csv

### ISSUE THREAD

**Issue by himkwtn** [thinc-org/open-reg-backend#62] opened 2019-10-25 11:51 UTC
file has missing .csv extension
thai language encoding

**Comment by fivechjr** [comment] 2019-10-25 13:03
Encoding seems to be fine. Also `.csv` exists. Can't reproduce the problem.

**Comment by fivechjr** [comment] 2019-10-28 06:24
Should we close this since it’s not our fault?

**Closed** 2019-10-28 07:06 UTC
Labels: bug
